### ISSUE TITLE
Ability to modify figure dimensions

### ISSUE THREAD

**Issue by samuel-emrys** [LaurentRDC/pandoc-plot#38] opened 2022-02-28 05:05 UTC
I can't currently see a good way to modify the dimensions of the figure. The equivalent latex code would be:

```
\begin{center}
    \includegraphics[width=200px]{./plots/pandocplot9558264899394455289.png}
\end{center}
```
Is it possible to proxy parameters like this to the underlying images? I'm having an issue where the figure is overflowing the boundaries of the slide similar to the following:
![Screenshot_20220228_153448](https://user-images.githubusercontent.com/36361864/155927076-c2a27a65-14d1-4579-a42c-a322db4b3df6.png)

This is more than just image overflow though, the caption "Figure 1: XYZ" is also being pushed off the page. Is there currently a way to rectify this?

**Comment by LaurentRDC** [comment] 2022-02-28 13:22
Hi Samuel,

`pandoc-plot` will let all 'unknown' parameter be passed to pandoc. For example:

````markdown
```{.matplotlib hello="world" foo=10}
fig = plt.figure(figsize=(10, 20)) # figure size in inches
...
```
````

would pass the parameters `hello` and `foo` to the underlying format. I can't test right now, but using this you should be able to have more control over the final conversion.

**Comment by samuel-emrys** [comment] 2022-03-05 12:27
Hi @LaurentRDC, a working example would be appreciated if you have the time. I haven't been able to get anything to work here - because graphviz doesn't allow you to specify a size i don't think I can modify the way the image is generated, and I can't easily see a way to influence the resulting latex with what you've described

**Comment by LaurentRDC** [comment] 2022-03-06 13:43
Here's a minimal example:

# Without controlling figure size

starting with this Markdown input:

````markdown
# Title

Paragraph

```{.graphviz}
digraph D {

  A [shape=diamond]
  B [shape=box]
  C [shape=circle]

  A -> B [style=dashed, color=grey]
  A -> C [color="black:invis:black"]
  A -> D [penwidth=5, arrowhead=none]

}
```
````

Render with `pandoc --filter pandoc-plot -i example.md -o example.tex`, gives the following LaTeX output:

```tex
\hypertarget{title}{%
\section{Title}\label{title}}

Paragraph

\begin{figure}
\centering
\includegraphics{plots/11623886912816197297.png}
\caption{}
\end{figure}
```

# With sizing

````markdown
# Title

Paragraph

```{.graphviz width=50mm height=60mm}
digraph D {

  A [shape=diamond]
  B [shape=box]
  C [shape=circle]

  A -> B [style=dashed, color=grey]
  A -> C [color="black:invis:black"]
  A -> D [penwidth=5, arrowhead=none]

}
```
````

Output looks like: 

```tex
\hypertarget{title}{%
\section{Title}\label{title}}

Paragraph

\begin{figure}
\centering
\includegraphics[width=50mm,height=60mm]{plots/11623886912816197297.png}
\caption{}
\end{figure}
```

As you can see, the parameters `width=50mm` and `height=60mm` (which are not understood by pandoc-plot) are passed to pandoc. 

Does this help?

**Comment by LaurentRDC** [comment] 2022-03-15 12:19
Given the solution above, I'll close this for now. Don't hesitate to re-open this issue if you need further help

**Comment by ronchaine** [comment] 2022-11-10 06:08
Would it be possible to add this example to the pandoc-plot documentation?  I don't expect everyone using pandoc-plot to be savvy enough to check github issues when they encounter this?

**Comment by paderevski** [comment] 2024-02-04 21:47
This behavior no longer exists in v 1.7.0. The example above did not pass through options to .tex

**Comment by fischerling** [comment] 2024-09-27 10:16
Can confirm that the solution above does not work for `pandoc 3.1.9` and `pandoc-plot 1.7.0`.
Would be great to get this behavior back. Unfortunatly, I am not a Haskel programmer and can not help that much.

**Comment by LaurentRDC** [comment] 2024-09-27 10:43
Let me take a look

**Comment by LaurentRDC** [comment] 2024-09-27 11:11
I can confirm this no longer works (currently using Pandoc 3.3 and pandoc-plot 1.9.0)

**Comment by LaurentRDC** [comment] 2024-09-27 11:40
I have found the source of the problem.
Extra parameters for figures can be passed down to pandoc, either to the outer 'Figure' block, the inner 'Image' block. I guess it used to not matter for the pandoc latex writer, but now it certainly does.

I will make a new release today (1.9.1). I have also added an example to the documentation.

**Comment by LaurentRDC** [comment] 2024-09-27 13:12
@fischerling please try out the new version (1.9.1) and let me know if the problem is fixed

**Comment by fischerling** [comment] 2024-09-27 15:24
Yes passing parameter to the image/figure works for `pandoc 3.19` and `pandoc-plot 1.9.1`.
Thanks you very much for your work and the quick response!

**Comment by LaurentRDC** [comment] 2024-09-27 15:25
No worries, somehow I missed the comments before yours.

Happy plotting!

**Closed by LaurentRDC** 2024-09-27 15:25 UTC
