### ISSUE TITLE
using packages other than Plots.jl may induce an error

### ISSUE THREAD

**Issue by YutaroIshihama** [LaurentRDC/pandoc-plot#15] opened 2020-12-22 07:15 UTC
If I try to use a CSV.jl package to read a csv datum from a file, it complains an error while executing the pandoc. The code inside my block starts like `using CSV, Plots`. But, `using CSV` may be a reason of the error. I wonder how to work it around. Thanks in advance for advice.

**Comment by LaurentRDC** [comment] 2020-12-22 16:08
Hello,

I'm no expert on Julia. Would you be able to answer the following questions:

* What error are you getting? Can you copy-paste the error?
* What version of pandoc / pandoc-plot are you using?
* Can you write down a simple exampel that reproduces the error, so I can test it here?

Thanks!

**Comment by YutaroIshihama** [comment] 2020-12-23 23:40
pandoc.exe 2.11.3.1 and pandoc-plot 1.0.0.0 (Win10 OS)

Minimum working example looks like,

```{.plotsjl}
using CSV, Plots # CSV package must be loaded here to read a csv file
mtx=CSV.read("foo.csv", header = false); mtx=Matrix(mtx)
plot(mtx[1:end,1], mtx[1:end,2]
```

assuming the content of `hoge.csv` file below;
```
1,3
2,5
3,4
```

This complains some error that will be posted later.

**Comment by YutaroIshihama** [comment] 2020-12-23 23:45
The error looks like: (unless loading CSV package, this did not occur)
```
ERROR | Running command
ERROR |     julia.exe "C:\Users\JohnDoe\AppData\Local\Temp\pandocplot1257825860.jl"
ERROR | ended with exit code ExitFailure 1
ERROR | *******
ERROR | ERROR: error initializing stdin in uv_dup: Unknown system error 50 (Unknown system error 50 50)
ERROR |
ERROR | *******
ERROR | Running command
ERROR |     julia.exe -e "using Plots"
ERROR | ended with exit code ExitFailure 1
ERROR | *******
ERROR | ERROR: error initializing stdin in uv_dup: Unknown system error 50 (Unknown system error 50 50)
ERROR |
ERROR | *******
ERROR | Julia/Plots.jl toolkit not installed.
```

**Comment by LaurentRDC** [comment] 2020-12-24 01:39
I think the issue is that this is not valid Julia, and the error is not being reported by pandoc-plot correctly. 

If I try the code above with CSV 0.8.2, `CSV.read` does not exist.

The following Markdown file works with pandoc-plot:

````markdown
# Test

```{.plotsjl}
using CSV, Plots, DataFrames
mtx=CSV.File("foo.csv", header = false) |> DataFrame
plot(mtx[1:end,1], mtx[1:end,2])
```
````

Can you confirm to me that the Julia code works in the Julia REPL? Maybe you are using an old version of CSV?

**Comment by YutaroIshihama** [comment] 2020-12-24 02:17
Thanks! I realized that the reason of failure comes from multi-statements using semicolon;
```
mtx=CSV.read("test.csv", header=false); mtx=Matrix(mtx)
```
By separating this into two lines,
```
mtx=CSV.read("test.csv", header=false)
mtx=Matrix(mtx)
```
this now **works**.

**Comment by LaurentRDC** [comment] 2020-12-24 13:04
Great, so I will close this issue.

**Closed by LaurentRDC** 2020-12-24 13:04 UTC
